Support SMTP configuration for password recovery
h-mdm/hmdm-docker pull request #21
Opened 2024-05-23 11:21 UTC by gainskills

Tested with 
https://hub.docker.com/r/hanbaobao2005/mdm/tags
and GMAIL SSL

works as expected
![verified](https://github.com/h-mdm/hmdm-docker/assets/1937472/003d5567-911d-4631-805e-7c755e8fb703)

2024-05-24 05:51 UTC, h-mdm requested changes
It is a good idea to add SMTP settings to docker environment. 

However currently they are commented in the XML config template (templates/conf/context_template.xml). Replacing the line containing spaces and one part of comments (docker-entrypoint.sh:50) is a bad idea, it makes the source code unclear and produces a potential source of bugs. For example, line 52 will never replace smtp.password because -->is not present in the template.

A better approach would be to uncomment SSL parameters and assign them the template values similar to other variables in that file:

    <Parameter name="smtp.host" value="_SMTP_HOST_"/>
    <Parameter name="smtp.port" value="_SMTP_PORT_"/>
    <Parameter name="smtp.ssl" value="_SMTP_SSL_"/>
    <Parameter name="smtp.starttls" value="_SMTP_STARTTLS_"/>
    <Parameter name="smtp.username" value="_SMTP_USERNAME_"/>
    <Parameter name="smtp.password" value="_SMTP_PASSWORD_"/>
    <Parameter name="smtp.from" value="_SMTP_FROM_"/>
    <Parameter name="smtp.ssl.protocols" value="_SMTP_SSL_VER_"/>

In the docker-entrypoint.sh, the _SMTP_*_ variables can be replaced with the environment variables. 

Default values of SMTP variables could be empty strings.

I believe that would be a more straightforward and clear approach.

2024-05-24 07:49 UTC, gainskills commented
thanks for your suggestions, will improve the PR

2024-08-16 06:22 UTC, gainskills commented
> It is a good idea to add SMTP settings to docker environment.
> 
> However currently they are commented in the XML config template (templates/conf/context_template.xml). Replacing the line containing spaces and one part of comments (docker-entrypoint.sh:50) is a bad idea, it makes the source code unclear and produces a potential source of bugs. For example, line 52 will never replace smtp.password because -->is not present in the template.
> 
> A better approach would be to uncomment SSL parameters and assign them the template values similar to other variables in that file:
> 
> ```
> <Parameter name="smtp.host" value="_SMTP_HOST_"/>
> <Parameter name="smtp.port" value="_SMTP_PORT_"/>
> <Parameter name="smtp.ssl" value="_SMTP_SSL_"/>
> <Parameter name="smtp.starttls" value="_SMTP_STARTTLS_"/>
> <Parameter name="smtp.username" value="_SMTP_USERNAME_"/>
> <Parameter name="smtp.password" value="_SMTP_PASSWORD_"/>
> <Parameter name="smtp.from" value="_SMTP_FROM_"/>
> <Parameter name="smtp.ssl.protocols" value="_SMTP_SSL_VER_"/>
> ```
> 
> In the docker-entrypoint.sh, the _SMTP_*_ variables can be replaced with the environment variables.
> 
> Default values of SMTP variables could be empty strings.
> 
> I believe that would be a more straightforward and clear approach.

I have updated the PR per suggestion, plz help to review it agin and advice.
Thanks,

2025-01-29 05:17 UTC, h-mdm reviewed
These updates are already done, along with some other improvements, please pull the latest update from the repository.

2025-02-01 02:29 UTC, gainskills commented
close this as it has been implemented in https://github.com/h-mdm/hmdm-docker/releases/tag/v0.1.5

2025-02-01 02:29 UTC, closed without merging